export const SHOW_COUNTRY_DETAILS = 'SHOW_COUNTRY_DETAILS'
export const SET_DATA_COUNTRY_SELECTED = 'SET_DATA_COUNTRY_SELECTED'
export const SET_FAVORITE_COUNTRY_SELECTED_ACTION = 'SET_FAVORITE_COUNTRY_SELECTED_ACTION'